name: ci

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  uiTests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - name: run tests
        run: ./gradlew :jcmake:testDebugUnitTest